version: '3.4'
services:
  api:
    container_name: 'klaypod_api_dev'
    image: 'arh714/klaypod-api-dev:1.0.0'
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    entrypoint: ['npm', 'run', 'start:dev']
    ports:
      - 8080:8080
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - src/config/env/.development.env
    command: npm run start:dev
    restart: unless-stopped
